name: Build
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Verify Shared Build
        run: npm run build:shared-ts
      - name: Verify UI Build
        run: npm run build:ui:gh
