name: Build
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build:ui:gh
      - run: npm run build:shared-ts
