name: Build
on:
  push:
    branches:
      - main
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install Dependencies
        run: npm ci
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd ui && npx semantic-release
  build:
    runs-on: ubuntu-latest
    needs:
      - version
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get Latest
        run: git pull
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build:ui:gh
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: ui/docs
